### ISSUE TITLE
Locazione repo

### ISSUE THREAD

**Issue by foxyseta** [VaiTon/unibocalendar#28]
La [pagina wiki](https://cartabinaria.github.io/wiki/applicativi-web/calendario/) menziona una wiki persa nelle sabbie del tempo: https://github.com/cartabinaria/UniboCalendar (prima del rinomino era "csunibo" ovviamente). Immagino fosse il nostro fork (v1) dell'originale progetto JavaScript di Francesco Bonzi: https://github.com/cartabinaria/unibo-calendar-legacy.

Ora che la v2 è più che stabile ha senso spostare la repo sotto @CartaBinaria come `cartabinaria/unibo-calendar` o qualcosa di simile? Fatto quello, possiamo aggiornare la wiki dicendo che il nostro è una riscrittura in Go del progetto originale. Se invece decidiamo di lasciarla qui, possiamo comunque aggiornare il link della wiki e spiegare perché la repo non sia sotto @cartabinaria.

**Comment by VaiTon** [comment]
Sinceramente mi piacerebbe non spostare il progetto completamente. Potremmo fare una fork su cartabinaria e a mano a mano farei PR per aggiornarlo. In questo modo anche su ansible si potrebbe mettere quello come repo da cui clonare il progetto.

**Comment by foxyseta** [comment]
Per me va benissimo anche così, sì. I progetti impattati sarebbero quindi solo la wiki, ansible, e informabot (che stampa nel messaggio anche un collegamento al sorgente)?

**Comment by VaiTon** [comment]
@foxyseta mi sembra di si. Procedo a fare il fork!

**Comment by foxyseta** [comment]
Se poi non hai avuto il tempo posso farlo anche io senza problemi.

**Comment by VaiTon** [comment]
@foxyseta ho fatto il fork. Manca aggiornare wiki e infra :)

**Comment by foxyseta** [comment]
Ottimo, grazie mille! Fai tu o io?

**Comment by VaiTon** [comment]
Faccio io, tranquillo!

**Comment by VaiTon** [comment]
Messo su infra. Adesso manca solo nella wiki. @foxyseta te ne puoi occupare tu o Alice?

**Comment by foxyseta** [comment]
Ci penso io!

**Comment by foxyseta** [comment]
Vedi https://github.com/cartabinaria/cartabinaria.github.io/pull/55.

**Comment by samuelemusiani** [comment]
Aggiornato anche il bot

**Comment by VaiTon** [comment]
Che cooperazione signori
