### ISSUE TITLE
Calendario singoli corsi

### ISSUE THREAD

**Issue by samuelemusiani** [VaiTon/unibocalendar#3]
Possibilità di avere dei link soltanto a dei singoli corsi invece che tutto un anno specifico. Aiuterebbe chi fuori corso deve soltanto dare alcuni esami specifici e non gli farebbe inserire il calendario completo con lezioni inutili

**Comment by VaiTon** [comment]
Con la 62449172a857111c93972a87dfcb83ce3c44acaa si puù adesso aggiungere un parametro alla query `subjects` che serve proprio a questo. Il parametro deve essere una stringa che contiene i codici dei corsi di cui si vuole ottenere il calendario separati da virgola.

Ho bisogno di aiuto per mostrarli nel sito web, visto che non ho idee.

```
webcal://.../cal/8004/1?subjects=19231,12345,...
```

**Comment by samuelemusiani** [comment]
Se mettessimo un menù a tendina di fianco ad ogni anno con scritto "Personalizza". Di predefinito ha tutti i corsi selezionati, però si posso deselezionare e in automatico il link si aggiorna lasciando solo quelli selezionati
