### ISSUE TITLE
bug: ics viewer usa orari sbagliati

### ISSUE THREAD

**Issue by ali-benny** [VaiTon/unibocalendar#8]
Visualizzando online un calendario, gli orari sono tutti indietro di 2 [è usato uct 0]

Dipende da:
- https://github.com/csunibo/dynamik/issues/57

**Comment by VaiTon** [comment]
Purtroppo il calendario online non è configurabile, quindi è necessario un calendario custom made: csunibo/dynamik#57

**Comment by VaiTon** [comment]
Risolto in #25
